import React, { createContext, useState, useContext } from 'react';

const ProductsContext = createContext();

export const useProducts = () => useContext(ProductsContext);

export const ProductsProvider = ({ children }) => {
  const [products, setProducts] = useState([
    {
      id: 1,
      name: 'Apicuria Natural Oral Spray',
      description: 'For Minor Mouth and Throat Irritation 12ml',
      price: 299,
      brand: 'APICURIA',
      category: 'Wellness',
      image: '/assets/images/products/featured1.jpg',
      dateListed: '2024-01-15',
      featured: true,
    },
    {
      id: 2,
      name: 'Areté Awaken Bath Salt',
      description: 'Good for Soak or Scrub, Deeply Exfoliates for Smooth Skin',
      price: 920,
      brand: 'ARETÉ',
      category: 'Bath',
      image: '/assets/images/products/featured1.jpg',
      dateListed: '2024-01-10',
      featured: false,
    },
    {
      id: 3,
      name: 'Areté Blue Butterfly Pea Tea',
      description: 'Boosts Metabolism & Hair Growth Boosts Metabolism & Hair Growth Boosts Metabolism & Hair Growth Boosts Metabolism & Hair Growth Boosts Metabolism & Hair Growth Boosts Metabolism & Hair Growth Boosts Metabolism & Hair Growth',
      price: 999,
      brand: 'ARETÉ',
      category: 'Tea',
      image: '/assets/images/products/featured2.jpg',
      dateListed: '2023-12-20',
      featured: true,
    },
    {
      id: 4,
      name: 'Areté Charcoal Organic Rice Soap',
      description: 'Handcrafted Soap Made With Essential Oils',
      price: 299,
      brand: 'ARETÉ',
      category: 'Soap',
      image: '/assets/images/products/featured1.jpg',
      dateListed: '2023-12-15',
      featured: false,
    },
    {
      id: 5,
      name: 'Areté Calm & Sleep Tea',
      description: 'Specialty Teas in Canister with Lavender and Chamomile',
      price: 499,
      brand: 'ARETÉ',
      category: 'Tea',
      image: '/assets/images/products/featured3.jpg',
      dateListed: '2024-01-05',
      featured: true,
    },
    {
      id: 6,
      name: 'Luxe Lavender Face Mask',
      description: 'Hydrating Face Mask with Lavender Extracts for Relaxing Skincare',
      price: 450,
      brand: 'Luxe Skincare',
      category: 'Skincare',
      image: '/assets/images/products/featured1.jpg',
      dateListed: '2024-02-01',
      featured: false,
    },
    {
      id: 7,
      name: 'HydroGlow Moisturizing Cream',
      description: 'Deep Moisture for All Skin Types, Non-Greasy',
      price: 800,
      brand: 'HydroGlow',
      category: 'Skincare',
      image: '/assets/images/products/featured1.jpg',
      dateListed: '2024-01-25',
      featured: false,
    },
    {
      id: 8,
      name: 'SootheWell Stress Relief Capsules',
      description: 'Herbal Capsules to Help Reduce Stress and Promote Calmness',
      price: 550,
      brand: 'SootheWell',
      category: 'Wellness',
      image: '/assets/images/products/featured1.jpg',
      dateListed: '2024-01-08',
      featured: false,
    },
    {
      id: 9,
      name: 'Areté Organic Green Tea',
      description: 'Rich in Antioxidants, Helps Boost Energy & Detoxify',
      price: 399,
      brand: 'ARETÉ',
      category: 'Tea',
      image: '/assets/images/products/featured1.jpg',
      dateListed: '2024-01-18',
      featured: true,
    },
    {
      id: 10,
      name: 'Nature’s Essence Organic Face Scrub',
      description: 'Gentle Exfoliation with Organic Natural Ingredients',
      price: 600,
      brand: 'Nature’s Essence',
      category: 'Skincare',
      image: '/assets/images/products/featured1.jpg',
      dateListed: '2024-02-03',
      featured: false,
    },
    {
      id: 11,
      name: 'Pure Bliss Tea Infuser Bottle',
      description: 'Portable Bottle for Tea Infusion with Built-in Strainer',
      price: 350,
      brand: 'Pure Bliss',
      category: 'Accessories',
      image: '/assets/images/products/featured1.jpg',
      dateListed: '2024-01-20',
      featured: true,
    },
    {
      id: 12,
      name: 'Vibrant Vitality Vitamin C Serum',
      description: 'Boosts Skin’s Radiance with Powerful Vitamin C and Hyaluronic Acid',
      price: 1_200,
      brand: 'Vibrant Vitality',
      category: 'Skincare',
      image: '/assets/images/products/featured1.jpg',
      dateListed: '2024-02-08',
      featured: false,
    },
    {
      id: 13,
      name: 'SootheWell Organic Sleep Drops',
      description: 'Natural Sleep Aid with Chamomile and Lavender',
      price: 450,
      brand: 'SootheWell',
      category: 'Wellness',
      image: '/assets/images/products/featured1.jpg',
      dateListed: '2024-01-15',
      featured: false,
    },
    {
      id: 14,
      name: 'Areté Premium Green Tea',
      description: 'High-Quality Green Tea Leaves, Rich in Antioxidants',
      price: 550,
      brand: 'ARETÉ',
      category: 'Tea',
      image: '/assets/images/products/featured1.jpg',
      dateListed: '2024-01-22',
      featured: false,
    },
    {
      id: 15,
      name: 'Areté Premium Green Tea',
      description: 'High-Quality Green Tea Leaves, Rich in Antioxidants',
      price: 550,
      brand: 'ARETÉ',
      category: 'Tea',
      image: '/assets/images/products/featured1.jpg',
      dateListed: '2024-01-22',
      featured: true,
    },
  ]);
  
  return (
    <ProductsContext.Provider value={{ products, setProducts }}>
      {children}
    </ProductsContext.Provider>
  );
};